name: gestion_espacios_app
description: Applicación multiplataforma para el proyecto de final de grado del CFGS Desarrollo de Aplicaciones.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  intl: ^0.18.1
  provider: ^6.0.5
  url_launcher: ^6.1.11
  http: ^0.13.0
  http_parser: ^4.0.2
  cupertino_icons: ^1.0.5
  table_calendar: ^3.0.9
  flutter_staggered_grid_view: ^0.4.0
  shared_preferences: ^2.1.1
  image_picker: ^0.8.7+5
  image_picker_for_web: ^2.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: KoHo
      fonts:
        - asset: assets/fonts/KoHo-Bold.ttf
        - asset: assets/fonts/KoHo-BoldItalic.ttf
        - asset: assets/fonts/KoHo-ExtraLight.ttf
        - asset: assets/fonts/KoHo-ExtraLightItalic.ttf
        - asset: assets/fonts/KoHo-Italic.ttf
        - asset: assets/fonts/KoHo-Light.ttf
        - asset: assets/fonts/KoHo-LightItalic.ttf
        - asset: assets/fonts/KoHo-Medium.ttf
        - asset: assets/fonts/KoHo-MediumItalic.ttf
        - asset: assets/fonts/KoHo-Regular.ttf
        - asset: assets/fonts/KoHo-SemiBold.ttf
        - asset: assets/fonts/KoHo-SemiBoldItalic.ttf
