version: "3.9"
services:
  api-users:
    build:
      context: ../../Microservicio-Usuarios
      dockerfile: ./docker/Dockerfile
    image: ruymi/api-users:latest
    container_name: api-users
    ports:
      - "8383:8383"
  api-spaces:
    build:
      context: ../../Microservicio-Salas
      dockerfile: ./docker/Dockerfile
    image: ruymi/api-spaces:latest
    container_name: api-spaces
    ports:
      - "8282:8282"
  api-bookings:
    build:
      context: ../../Microservicio-Reservas
      dockerfile: ./docker/Dockerfile
    image: ruymi/api-bookings:latest
    container_name: api-bookings
    ports:
      - "8181:8181"
  gateway:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    image: ruymi/gateway:latest
    container_name: gateway
    ports:
      - "1212:1212"
    depends_on:
      - api-spaces
      - api-users
      - api-bookings